/**
 * 🔴 🔴 🔴
 * DON'T USE THAT FILE FOR PRODUCTION BUILDS.
 * INSTEAD inferno-compat.tsx should be used
 */

// tslint:disable
import {
  Children,
  Component,
  EMPTY_OBJ,
  Fragment,
  PropTypes,
  PureComponent,
  // Internal methods
  _CI,
  _HI,
  _M,
  _MCCC,
  _ME,
  _MFCC,
  _MP,
  _MR,
  _MT,
  __render,
  // Public methods
  cloneElement,
  cloneVNode,
  createClass,
  createComponentVNode,
  createElement,
  createFactory,
  createFragment,
  createPortal,
  createRef,
  createRenderer,
  createTextVNode,
  createVNode,
  directClone,
  findDOMNode,
  findDOMfromVNode,
  forwardRef,
  getFlagsForElementVnode,
  hydrate,
  isValidElement,
  linkEvent,
  normalizeProps,
  options,
  render,
  rerender,
  unmountComponentAtNode,
  unstable_renderSubtreeIntoContainer,
  version,
} from 'inferno-compat/dist/index.dev.esm';
import createContext from 'create-inferno-context';

const unstable_batchedUpdates = null;

export {
  Children,
  Component,
  EMPTY_OBJ,
  Fragment,
  PropTypes,
  PureComponent,
  // Internal methods
  _CI,
  _HI,
  _M,
  _MCCC,
  _ME,
  _MFCC,
  _MP,
  _MR,
  _MT,
  __render,
  // Public methods
  cloneElement,
  cloneVNode,
  createClass,
  createComponentVNode,
  createElement,
  createFactory,
  createFragment,
  createPortal,
  createRef,
  createRenderer,
  createTextVNode,
  createVNode,
  directClone,
  findDOMNode,
  findDOMfromVNode,
  forwardRef,
  getFlagsForElementVnode,
  hydrate,
  isValidElement,
  linkEvent,
  normalizeProps,
  options,
  render,
  rerender,
  unmountComponentAtNode,
  unstable_renderSubtreeIntoContainer,
  version,
  createContext, // <-- Add it here
  unstable_batchedUpdates,
};

export default {
  Children,
  Component,
  EMPTY_OBJ,
  Fragment,
  PropTypes,
  PureComponent,
  // Internal methods
  _CI,
  _HI,
  _M,
  _MCCC,
  _ME,
  _MFCC,
  _MP,
  _MR,
  _MT,
  __render,
  // Public methods
  cloneElement,
  cloneVNode,
  createClass,
  createComponentVNode,
  createElement,
  createFactory,
  createFragment,
  createPortal,
  createRef,
  createRenderer,
  createTextVNode,
  createVNode,
  directClone,
  findDOMNode,
  findDOMfromVNode,
  forwardRef,
  getFlagsForElementVnode,
  hydrate,
  isValidElement,
  linkEvent,
  normalizeProps,
  options,
  render,
  rerender,
  unmountComponentAtNode,
  unstable_renderSubtreeIntoContainer,
  version,
  createContext, // <-- And here
  unstable_batchedUpdates,
};
